### ISSUE TITLE
Fix dark mode

### ISSUE THREAD

**Issue by ayushknath** [cyberbuddy-manas/notes#10]
I recently made a PR #6 that added dark mode functionality to the app but later another PR that was merged probably broke it. If you would assign this issue to me, I can work it out.

**Comment by cyberbuddy-manas** [comment]
Yeah please, I was about to revert all of that since it was my mistake. If you can work on this one it would be a great help!!

**Comment by ayushknath** [comment]
Yeah on it...

**Comment by cyberbuddy-manas** [comment]
@ayushknath Thanks a lot mann!!

**Comment by ayushknath** [comment]
> @ayushknath Thanks a lot mann!!

Mention not. Just excited to contribute to open source in whichever way possible.

**Comment by cyberbuddy-manas** [comment]
Hi @ayushknath what's the status of hacktoberfest for this pr, did it get accepted or what?

**Comment by ayushknath** [comment]
No it did not get accepted

**Comment by cyberbuddy-manas** [comment]
@ayushknath can please share what exactly was the status? Did it get excluded, or not accepted or not participating

**Comment by ayushknath** [comment]
Not participating @cyberbuddy-manas

**Comment by ayushknath** [comment]
Now the 7 days review timer has begun.

**Comment by ayushknath** [comment]
No it did not get accepted. But the previous one Issue #6 got accepted.
