### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by cyberbuddy-manas** [cyberbuddy-manas/notes#3]
If you are a beginner and have basic knowledge of HTML, CSS and JS, you can probably try working on adding dark mode to the application. This will also be accepted in hacktoberfest2022 so make sure you contribute!!

**Comment by Abdirizaks12** [comment]
assign me

**Comment by cyberbuddy-manas** [comment]
@Abdirizaks12 Great, here you go!!!

**Comment by Abdirizaks12** [comment]
thanks. am a beginner,it will take time but i'll finish it.

**Comment by NayanDeshmukh2001** [comment]
i did many projects like this please assign it to me

**Comment by cyberbuddy-manas** [comment]
Hi @NayanDeshmukh2001 it's already assigned, so try adding any other functionality or maybe improve some bug you find in the site which you're capable of fixing. Keep contributing
