### ISSUE TITLE
Add footer to the site

### ISSUE THREAD

**Issue by radhika141** [cyberbuddy-manas/notes#38]
Pls assign this issue to me

**Comment by cyberbuddy-manas** [comment]
Hi @radhika141, footer to the website is already added, so kindly share some description about the idea or work on some different feature. You can work on UI or maybe on the functionality

**Comment by biswajit150803** [comment]
I want to add footer to this site where links to ur social media handles for contacting will be there and also newsletter part will be there.Plz assign me this
