### ISSUE TITLE
Improve responsiveness

### ISSUE THREAD

**Issue by cyberbuddy-manas** [cyberbuddy-manas/notes#4]
This one is a tough task.............for most of the people but not you. If you are a beginner and want to contribute in hacktoberfest, you may like to improve the responsiveness of the application. It will be accepted in hacktobefest2022 so make sure you contribute!!

**Comment by AnkushGoel251** [comment]
I want to work on this, please assign this to me.

**Comment by Abhishekvermaa** [comment]
pls assign me this issue if someone is not working

**Comment by cyberbuddy-manas** [comment]
Hi @AnkushGoel251 since you came first for this one, I will be providing this issue to you!! Go ahead mann

**Comment by cyberbuddy-manas** [comment]
@Abhishekvermaa Kindly go thorough other issues or maybe try adding your own. You can work on several features or look for bugs.

**Comment by AnkushGoel251** [comment]
Thanks for assiging, It will take some time but i will try to do it asap

**Comment by MAYANK816** [comment]
Hey there,  want to work on this, please assign this to me, I will do my best .

**Comment by cyberbuddy-manas** [comment]
This issue has been resolved. Thanks guys!! @MAYANK816 Look for more issues in the application or go through the other unassigned issues. Your contribution really matters so in case you need some help then open a new issue asking for the same.
