### ISSUE TITLE
Fix the date issue

### ISSUE THREAD

**Issue by cyberbuddy-manas** [cyberbuddy-manas/notes#5]
As you can see that the date is hard coded, I would really like if it could capture the current date or maybe the time as well and act dynamically. It will be valid for hacktoberfest2022

![image](https://user-images.githubusercontent.com/70315395/193511311-8b47b80c-ba82-470a-8d3a-08a8636aebd2.png)

**Comment by hardiksharma11** [comment]
Hii, I would like to work on this issue. Plz assign this to me...

**Comment by cyberbuddy-manas** [comment]
Sure @hardiksharma11, rock on and in case you need any help just text me over here in the conversation.

**Comment by sayan404** [comment]
I would like to solve this issue ... please assign me this issue @cyberbuddy-manas

**Comment by Hussain6** [comment]
Hi! i would like to work on this issue can you assign this to me

**Comment by cyberbuddy-manas** [comment]
Hi @sayan404 @Hussain6, I have already assigned the issue but in case I don't receive a contribution soon, I'll reassign. Till then you can think on adding various features or maybe try finding a bug other than the ones already listed.
